### ISSUE TITLE
Toolchain's Erlang crypto module fails on Fedora 23

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves-toolchain#7]
The failure looks like this when building:

```
17:18:15.290 [error] Unable to load crypto library. Failed with error:
":load_failed, Failed to load NIF library /home/ricarus/.nerves/toolchains/nerves-arm-unknown-linux-gnueabihf-linux-x86_64-v0.5.0/lib/erlang/bin/../lib/crypto-3.6.1/priv/lib/crypto: 'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.


17:18:15.304 [warn]  The on_load function for module crypto returned {:error,
 {:load_failed,
  'Failed to load NIF library /home/ricarus/.nerves/toolchains/nerves-arm-unknown-linux-gnueabihf-linux-x86_64-v0.5.0/lib/erlang/bin/../lib/crypto-3.6.1/priv/lib/crypto: \'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory\''}}

** (UndefinedFunctionError) undefined function :crypto.verify/5 (module :crypto is not available)
    (crypto) :crypto.verify(:rsa, :sha512, "0.10.0,1235bccae2fb670207cd3b1c7e56afc7bf8aae114d288f9603c86279681b5ee8d892319262e2a1c98d7961dbf4771210856484c781bd7860704402d12c2b5b95,1.0.0\n0.10.0,90665a38f682997ca2985b96badc81d222bd33b13e56f73e1981431291dd9e562788ed28c3c3ae310c23788dfa8162bab7dffc2ee74a1d728600262fc4fa350d,1.1.0\n0.10.0,bb2f9a49b5ff436f4555c655c85f2d8e2830f6bf41c4b4890cb88892e372a4b3be0814c7239aa91c17891cdfa410ac7d1de662c29d531b9c028347bdcdd893a1,1.2.0\n", <<22, 14, 99, 132, 66, 206, 33, 129, 219, 146, 204, 250, 17, 43, 11, 153, 10, 214, 169, 142, 134, 230, 88, 65, 85, 151, 155, 150, 174, 30, 136, 139, 1, 141, 240, 222, 68, 213, 143, 230, 12, 192, 210, 28, 94, 5, 164, 184, 162, 42, ...>>, [65537, 22511816799652361022798694196318211537616412647244751881312633299312413595030102393732362885655223577569373471110521230037036521318790022942469131024250515121203912460395767501419984828131558412939281157597078145271458771838368846651512970136828209753916563559350757069984478780896921983736209192531733220246713682695165060696499110997206068226426173314938615058793140493890694975760413596596496242653027499830433842734195456057519083832841921156182096655559268898249524720518685001721720608123581799076801732873918664570521827298384777839147673077508779554792336681028366980185140494520907144288473261434560461317013])
    (elixir) lib/enum.ex:2414: Enum.do_any?/2
    (mix) lib/mix/local.ex:93: Mix.Local.find_matching_versions_from_signed_csv!/2
    (mix) lib/mix/tasks/local.hex.ex:30: Mix.Tasks.Local.Hex.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

After some debugging, it was found that the OpenSSL libcrypto.so shared library has a different file extension on Debian and Fedora systems. Debian uses the naming `libcrypto.so.1.0.0` and Fedora has `libcrypto.so.10` or `libcrypto.so.1.0.2e`. Copying a `libcrypto.so.1.0.0` from another system to Fedora was a workaround.

**Comment by fhunleth** [comment]
My current thought on this is to revisit the decision to bundle Erlang with the crosscompiler. The original decision was based on ensuring consistent builds, but some of the issues like this one weren't foreseen until we actually started doing it. We should be able to ensure consistent builds by checking the Erlang compiler version before building. This is weakly done in the `nerves-env.sh` script, but the comparison may be too strict and the error is ignored when building through `bake`.

**Comment by fhunleth** [comment]
Per conversation with @mobileoverlord, we're proceeding by removing Erlang and Elixir from the toolchain builds. `bake` will provide consistency between builds by handling Erlang and Elixir versions. Checks are being added to `nerves-system-br` to require matching Erlang major releases between host and target, and issue a warning when the Erlang minor release differs.

**Comment by fhunleth** [comment]
We have had v0.6.0 toolchains that remove Erlang and Elixir since last weekend. Technically this fixes this bug since we're no longer using openssl in the toolchain. @mobileoverlord and I want to get in a few other changes to nerves-system-br configuration before we declare success, though. I got distracted on other issues this week and didn't get to finishing this yet. Feel free to modify your config to use the v0.6.0 toolchain and your host's version of erlang and elixir to get past this if this is blocking you. (I suspect not, since you copied a libcrypto from another system to work around it)

**Comment by fhunleth** [comment]
Closing old issue that was fixed.
